package com.example.modid;

// This file is a stub left from the RFG template. It is not part of the MFFS mod.
// The Tags class (com.example.modid.Tags) is generated by the build system.
// In 1.12.2 RFG projects, Tags is generated during buildSrc setup.

public final class ExampleMod {
    private ExampleMod() {}
}
