package dev.su5ed.mffs;

// =============================================================================
// 1.12.2 Backport: MFFSMod entry point
// The original 1.21.x NeoForge implementation is commented out below.
// 1.21.x used constructor-injection (IEventBus, ModContainer) which does not
// exist in Forge 1.12.2. The 1.12.2 pattern uses @Mod.EventHandler lifecycle
// methods: preInit / init / postInit.
// =============================================================================

import dev.su5ed.mffs.network.Network;
import dev.su5ed.mffs.setup.ModCapabilities;
import dev.su5ed.mffs.setup.ModItems;
import dev.su5ed.mffs.setup.ModObjects;
import dev.su5ed.mffs.setup.ModTags;
import dev.su5ed.mffs.util.FrequencyGrid;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import dev.su5ed.mffs.command.MffsCommand;
import net.minecraftforge.fml.common.event.FMLServerAboutToStartEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.minecraftforge.fml.common.network.NetworkRegistry;
import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.oredict.OreDictionary;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

// TODO: uncomment once Tags class is generated by RFG injectTags task:
// import dev.su5ed.mffs.Tags;

@Mod(
    modid   = MFFSMod.MODID,
    name    = MFFSMod.NAME,
    version = MFFSMod.VERSION,
    // Require Forge 1.12.2 build 2847 or newer
    dependencies = "required-after:forge@[14.23.5.2847,);"
)
public final class MFFSMod {
    // TODO: Replace literals with Tags.MOD_ID / Tags.MOD_NAME / Tags.VERSION
    //       once Tags.java is generated by the RFG build.
    public static final String MODID   = "mffs";
    public static final String NAME    = "Modular Force Field System";
    public static final String VERSION = "1.0.0";

    private static final String TOP_MODID = "theoneprobe";

    public static final Logger LOGGER = LogManager.getLogger(MODID);

    @Instance
    public static MFFSMod INSTANCE;

    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        // Load config from disk
        MFFSConfig.load(event.getSuggestedConfigurationFile());

        // Register capabilities
        ModCapabilities.register();

        // Register TileEntity classes
        ModObjects.registerTileEntities();

        // Register event handlers on the Forge event bus
        MinecraftForge.EVENT_BUS.register(new ForgeEventHandler());
    }

    @EventHandler
    public void init(FMLInitializationEvent event) {
        // Register GUI handler
        NetworkRegistry.INSTANCE.registerGuiHandler(this, new MFFSGuiHandler());

        // Setup network channel
        Network.init();

        // 1.12 crafting recipes use OreDictionary for steel ingots (only if not disabled).
        if (!MFFSConfig.disableSteelItems) {
            OreDictionary.registerOre(ModTags.INGOTS_STEEL, ModItems.STEEL_INGOT);
            // 1.12 furnace recipes are registered in code.
            GameRegistry.addSmelting(ModItems.STEEL_COMPOUND, new ItemStack(ModItems.STEEL_INGOT), 0.5F);
        }
    }

    @EventHandler
    public void serverStarting(FMLServerStartingEvent event) {
        event.registerServerCommand(new MffsCommand());
    }

    @EventHandler
    public void serverAboutToStart(FMLServerAboutToStartEvent event) {
        // Reset the FrequencyGrid before world/chunk loading to prevent stale references.
        // Must be FMLServerAboutToStartEvent (not FMLServerStartingEvent) because in 1.12.2,
        // FMLServerStartingEvent fires AFTER spawn chunks load. If we reinitiate after chunk
        // loading, TileEntities that registered in onLoad() have their entries wiped.
        FrequencyGrid.reinitiate();
    }

    @EventHandler
    public void postInit(FMLPostInitializationEvent event) {
        // TODO: Send IMC to TheOneProbe if loaded
        // 1.21.x used:
        //   if (ModList.get().isLoaded(TOP_MODID)) {
        //       InterModComms.sendTo(TOP_MODID, "getTheOneProbe", MFFSProbeProvider::new);
        //   }
        // 1.12.2 equivalent via FML IMC:
        //   if (Loader.isModLoaded(TOP_MODID)) {
        //       FMLInterModComms.sendFunctionMessage(TOP_MODID, "getTheOneProbe",
        //           "dev.su5ed.mffs.compat.MFFSProbeProvider");
        //   }
    }

    /**
     * Creates a {@link ResourceLocation} namespaced to this mod.
     * 1.21.x equivalent: Identifier.fromNamespaceAndPath(MODID, path)
     */
    public static ResourceLocation location(String path) {
        return new ResourceLocation(MODID, path);
    }
}
